apiVersion: v2
description: Helm Chart for Codefresh On-Prem
name: codefresh
version: 2.10.5
keywords:
  - codefresh
home: https://codefresh.io/
icon: https://avatars1.githubusercontent.com/u/11412079?v=3
sources:
  - https://github.com/codefresh-io/codefresh-onprem-helm
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
appVersion: 0.0.0
annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/alternativeName: "codefresh-onprem"
  artifacthub.io/containsSecurityUpdates: "true"
  # supported kinds are added, changed, deprecated, removed, fixed and security.
  # artifacthub.io/changes: |
  #   - kind:
  #     description: ""
  artifacthub.io/changes: |-
    - kind: deprecated
    description: '"push-tag" step is no longer supported.'
    - kind: removed
    description: 'Remove "docker-tag-pusher" image.'
    - kind: changed
    description: 'Update "engine" to 3.0.1.'
    - kind: changed
    description: 'Update "cf-git-cloner" to 10.3.7.'
    - kind: changed
    description: 'Update "dind" to 29.2.0-3.0.10 with Docker Engine v29.2.0.'
    links:
      - name: Docker Engine v29 release notes
        url: https://docs.docker.com/engine/release-notes/29/
    - kind: security
    description: 'Fix various security vulnerabilities in multiple runtime components.'
dependencies:
  - name: cf-common
    repository: oci://quay.io/codefresh/charts
    version: 0.31.0
  - name: internal-gateway
    repository: oci://quay.io/codefresh/charts
    version: 0.12.2
    condition: internal-gateway.enabled
  - name: consul
    version: 11.4.32
    repository: https://charts.bitnami.com/bitnami
    condition: consul.enabled
  - name: mongodb
    version: 15.6.26
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled,mongo.enabled,global.mongoDeploy
  - name: postgresql
    version: 16.7.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql-ha
    version: 12.0.4
    repository: oci://quay.io/codefresh/charts
    condition: postgresql-ha.enabled
  - name: redis
    version: 20.13.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis-ha
    repository: https://dandydeveloper.github.io/charts
    version: 4.26.1
    condition: redis-ha.enabled
  - name: rabbitmq
    version: 15.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: nats
    version: 9.0.28
    repository: https://charts.bitnami.com/bitnami
    condition: nats.enabled
  - name: builder
    repository: oci://quay.io/codefresh/charts
    condition: builder.enabled
    version: 2.0.0
  - name: ingress-nginx
    version: 4.13.5
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: cluster-providers
    version: 1.19.5-onprem-5b312e5
    repository: oci://quay.io/codefresh/charts
    condition: cluster-providers.enabled
  - name: kube-integration
    version: 1.33.6-onprem-813166a
    repository: oci://quay.io/codefresh/charts
    condition: kube-integration.enabled
  - name: charts-manager
    version: 1.26.4-onprem-7e6d100
    repository: oci://quay.io/codefresh/charts
    condition: charts-manager.enabled
  - name: cfsign
    version: 1.8.15
    repository: oci://quay.io/codefresh/charts
    condition: cfsign.enabled
  - name: tasker-kubernetes
    version: 1.28.4-onprem-7450ced
    repository: oci://quay.io/codefresh/charts
    condition: tasker-kubernetes.enabled
  - name: context-manager
    version: 2.37.4-onprem-7b66875
    repository: oci://quay.io/codefresh/charts
    condition: context-manager.enabled
  - name: pipeline-manager
    version: 3.143.4-onprem-8582ab7
    repository: oci://quay.io/codefresh/charts
    condition: pipeline-manager.enabled
  - name: gitops-dashboard-manager
    version: 1.16.4-onprem-48d7cb3
    repository: oci://quay.io/codefresh/charts
    condition: gitops-dashboard-manager.enabled
  - name: cfapi
    alias: cfapi
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi.enabled
  - name: cfapi
    alias: cfapi-auth
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-auth.enabled
  - name: cfapi
    alias: cfapi-internal
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-internal.enabled
  - name: cfapi
    alias: cfapi-ws
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-ws.enabled
  - name: cfapi
    alias: cfapi-admin
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-admin.enabled
  - name: cfapi
    alias: cfapi-endpoints
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-endpoints.enabled
  - name: cfapi
    alias: cfapi-terminators
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-terminators.enabled
  - name: cfapi
    alias: cfapi-sso-group-synchronizer
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-sso-group-synchronizer.enabled
  - name: cfapi
    alias: cfapi-buildmanager
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-buildmanager.enabled
  - name: cfapi
    alias: cfapi-cacheevictmanager
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-cacheevictmanager.enabled
  - name: cfapi
    alias: cfapi-eventsmanagersubscriptions
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-eventsmanagersubscriptions.enabled
  - name: cfapi
    alias: cfapi-kubernetesresourcemonitor
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetesresourcemonitor.enabled
  - name: cfapi
    alias: cfapi-environments
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-environments.enabled
  - name: cfapi
    alias: cfapi-gitops-resource-receiver
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-gitops-resource-receiver.enabled
  - name: cfapi
    alias: cfapi-downloadlogmanager
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-downloadlogmanager.enabled
  - name: cfapi
    alias: cfapi-teams
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-teams.enabled
  - name: cfapi
    alias: cfapi-kubernetes-endpoints
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-kubernetes-endpoints.enabled
  - name: cfapi
    alias: cfapi-test-reporting
    version: 21.293.11-onprem-1169fc9
    repository: oci://quay.io/codefresh/charts
    condition: cfapi-test-reporting.enabled
  - name: cfui
    version: 14.99.58
    repository: oci://quay.io/codefresh/charts
    condition: cfui.enabled
  - name: k8s-monitor
    version: 4.11.20-onprem-101e14c
    repository: oci://quay.io/codefresh/charts
    condition: k8s-monitor.enabled
  - name: runtime-environment-manager
    version: 3.44.5-onprem-825697e
    repository: oci://quay.io/codefresh/charts
    condition: runtime-environment-manager.enabled
  - name: cf-broadcaster
    version: 1.14.5-onprem-0dcf808
    repository: oci://quay.io/codefresh/charts
    condition: cf-broadcaster.enabled
  - name: helm-repo-manager
    version: 0.23.2-onprem-6c4165f
    repository: oci://quay.io/codefresh/charts
    condition: helm-repo-manager.enabled
  - name: hermes
    version: 0.21.24-onprem-3955c67
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: nomios
    version: 0.11.14-onprem-6a8422e
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: cronus
    version: 0.8.14-onprem-2eb7d75
    repository: oci://quay.io/codefresh/charts
    condition: hermes.enabled
  - name: cf-platform-analytics
    alias: cf-platform-analytics-platform
    version: 0.52.4-onprem-8313be2
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: cf-platform-analytics
    alias: cf-platform-analytics-etlstarter
    version: 0.52.4-onprem-8313be2
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: argo-platform
    version: 1.3978.0-onprem-d51e55f
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: argo-hub-platform
    version: 0.1.30
    repository: oci://quay.io/codefresh/charts
    condition: argo-platform.enabled
  - name: cf-oidc-provider
    repository: oci://quay.io/codefresh/charts
    version: 0.1.0
    condition: cf-oidc-provider.enabled
  - name: mailer
    version: "1.22.2"
    repository: oci://quay.io/codefresh/charts
    condition: mailer.enabled
  - name: payments
    version: "2.25.3"
    repository: oci://quay.io/codefresh/charts
    condition: payments.enabled
  - name: segment-reporter
    version: "1.19.1"
    repository: oci://quay.io/codefresh/charts
    condition: segment-reporter.enabled
  - name: salesforce-reporter
    version: "1.32.1"
    repository: oci://quay.io/codefresh/charts
    condition: salesforce-reporter.enabled
